export interface MemberPaged  {
    masterPatientID: number,
    memberFirstName: string,
    memberMiddleName: string,
    memberLastName: string,
    mmiS_MMIS_ID: string,
    ccaid: number,
    product: string,
    enrollStartDate: string,
    enrollEndDate: string,
    dob: string,
    dod: string,
    ratingCategory: string,
    region: string,
    memberEnrollmentStatus: string,
    totalAssigned: number
    totalDiscrepancies: number,
    maxAging: number,
    absoluteVarianceSum: number,
};


export interface Member {
    masterPatientID: number,
    memberFirstName: string,
    memberMiddleName: string,
    memberLastName: string,
    gender: string
    mmiS_MMIS_ID: string,
    ccaid: number,
    product: string,
    enrollStartDate: string,
    enrollEndDate: string,
    dob: string,
    dod: string,
    ratingCategory: string,
    ratingCategoryStartDate: string,
    ratingCategoryEndDate: string,
    region: string,
    regionStartDate: string,
    regionEndDate: string,
    patientPay: number,
    patientPayStartDate: string,
    patientPayEndDate: string,
    patientSpendDown: number,
    patientSpendDownStartDate: string,
    patientSpendDownEndDate: string,
    rateCardID: number,
    ccaRateCellID: number,
    ccaRegionID: number,
    amount: number,
    startDate: string,
    endDate: string,
    activeFlag: string,
    memberEnrollmentStatus: string,
    totalDiscrepancies: number,
    totalAssigned: number,
    maxAging: number,
    absoluteVarianceSum: number,
};

export interface MemberName {
    masterPatientID: number,
    memberFirstName: string,
    memberMiddleName: string,
    memberLastName: string,
    mmiS_MMIS_ID: string,
    ccaid: number,
}