import { DisElement } from './MOCK_DATA';

  export interface DisElement {
    lastName: string;
    firstName: string;
    mmis_id: number;
    cca_id: number;
    program: string;
    month: string;
    org_ratecell: string;
    org_region: string;
    org_premium: number;
    org_pp: number;
    org_sp: number;
    payor_ratecell: string;
    payor_region: string;
    payor_premium: number;
    payor_pp: number;
    payor_sp: number;
    payor_paid: number;
    variance: number;
  }

export interface PeriodicElement {
    lastName: string;
    firstName: string;
    mmis_id: number;
    cca_id: number;
    program: string;
    dob: string;
    enrollmentStart: string;
    enrollmentEnd: string;
    ratecell: string;
    region: string;
    total_d: number;
    aging: number;
    amount: number;
    org_premium: number;
    org_pp: number;
    org_sp: number;
    discrepancies: DisElement[];
  }




let MemberData: PeriodicElement[] = [
  {
    "program": "ICO",
    "firstName": "Marilyn",
    "lastName": "Chaney",
    "mmis_id": 100036076758,
    "cca_id": 5360025984,
    "dob": "1968-05-18",
    "enrollmentStart": "2017-10-01",
    "enrollmentEnd": "2019-04-01",
    "ratecell": "DC1",
    "region": "NA",
    "org_premium": 562.18,
    "org_pp": 88.7,
    "org_sp": 88.1,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-06-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 24.67,
        "org_sp": 0,
        "payor_ratecell": "DF1",
        "payor_region": "West",
        "payor_premium": 2808.58,
        "payor_pp": 24.67,
        "payor_sp": 0,
        "payor_paid": 2808.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 24.67,
        "org_sp": 0,
        "payor_ratecell": "DF1",
        "payor_region": "West",
        "payor_premium": 2808.58,
        "payor_pp": 24.67,
        "payor_sp": 0,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 24.67,
        "org_sp": 0,
        "payor_ratecell": "DF1",
        "payor_region": "West",
        "payor_premium": 2808.58,
        "payor_pp": 24.67,
        "payor_sp": 0,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 24.67,
        "org_sp": 0,
        "payor_ratecell": "DF1",
        "payor_region": "West",
        "payor_premium": 2808.58,
        "payor_pp": 24.67,
        "payor_sp": 0,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-08-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 24.67,
        "org_sp": 0,
        "payor_ratecell": "DF1",
        "payor_region": "West",
        "payor_premium": 2808.58,
        "payor_pp": 24.67,
        "payor_sp": 0,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 24.67,
        "org_sp": 0,
        "payor_ratecell": "DF1",
        "payor_region": "West",
        "payor_premium": 2808.58,
        "payor_pp": 24.67,
        "payor_sp": 0,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 66.94,
        "org_sp": 73.69,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 133.73,
        "payor_sp": 66.55,
        "payor_paid": 549.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Tameka",
    "lastName": "Tyson",
    "mmis_id": 100021362160,
    "cca_id": 5360955934,
    "dob": "1971-02-02",
    "enrollmentStart": "2018-04-01",
    "enrollmentEnd": "2019-03-01",
    "ratecell": "R2D2",
    "region": "Boston",
    "org_premium": 6755.9,
    "org_pp": 52.47,
    "org_sp": 5.7,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-07-01",
        "org_ratecell": "DC2A",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 130.32,
        "org_sp": 87.89,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 2371.4,
        "payor_pp": 18.53,
        "payor_sp": 14.31,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-03-01",
        "org_ratecell": "DC2A",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 33.23,
        "org_sp": 45,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 6.61,
        "payor_sp": 63.54,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 12.34,
        "org_sp": 41.8,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 156.67,
        "payor_sp": 58.82,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 120.28,
        "org_sp": 33.13,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 186.24,
        "payor_sp": 54.09,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-08-01",
        "org_ratecell": "DC1",
        "org_region": "Cape",
        "org_premium": 2808.58,
        "org_pp": 150.71,
        "org_sp": 21.77,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 57.93,
        "payor_sp": 26.38,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 51.55,
        "org_sp": 73.2,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 100.3,
        "payor_sp": 53.91,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 89.31,
        "org_sp": 26.95,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 83.94,
        "payor_sp": 90.44,
        "payor_paid": 328.36,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Paige",
    "lastName": "Rios",
    "mmis_id": 100068035766,
    "cca_id": 5362829115,
    "dob": "1987-06-01",
    "enrollmentStart": "2017-10-01",
    "enrollmentEnd": "2018-12-01",
    "ratecell": "R2D2",
    "region": "Non-Bos",
    "org_premium": 842.29,
    "org_pp": 134.8,
    "org_sp": 89.74,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-04-01",
        "org_ratecell": "DC2A",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 67.05,
        "org_sp": 55.05,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 177.6,
        "payor_sp": 95.82,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC1",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 179.81,
        "org_sp": 7.57,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 166.58,
        "payor_sp": 81.69,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 146.46,
        "org_sp": 11.75,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 6.23,
        "payor_sp": 46.59,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 2.16,
        "org_sp": 78.1,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 71.65,
        "payor_sp": 35.79,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 128.46,
        "org_sp": 6.57,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 70.34,
        "payor_sp": 34.11,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 9.56,
        "org_sp": 21.45,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 95.83,
        "payor_sp": 37.49,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 6755.9,
        "org_pp": 77.61,
        "org_sp": 99.83,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 2371.4,
        "payor_pp": 47.64,
        "payor_sp": 19.81,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 19.47,
        "org_sp": 33.42,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 99.7,
        "payor_sp": 31.42,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 147.12,
        "org_sp": 88.64,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 102.92,
        "payor_sp": 67.42,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 125.93,
        "org_sp": 5.27,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 122.82,
        "payor_sp": 79.76,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC2A",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 141.38,
        "org_sp": 59.43,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 153.45,
        "payor_sp": 60.76,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "Cape",
        "org_premium": 2808.58,
        "org_pp": 95.89,
        "org_sp": 24.94,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 108.11,
        "payor_sp": 45.7,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Casandra",
    "lastName": "Collins",
    "mmis_id": 100033577125,
    "cca_id": 5363100719,
    "dob": "1963-10-02",
    "enrollmentStart": "2017-01-01",
    "enrollmentEnd": "2018-10-01",
    "ratecell": "DC2A",
    "region": "Cape",
    "org_premium": 6755.9,
    "org_pp": 56.19,
    "org_sp": 2.29,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC2A",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 122.17,
        "org_sp": 90.88,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 7.49,
        "payor_sp": 35.46,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 39.02,
        "org_sp": 96.78,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 11.6,
        "payor_sp": 6.73,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 169.28,
        "org_sp": 51.82,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 77.05,
        "payor_sp": 32.41,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-06-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 6755.9,
        "org_pp": 146.59,
        "org_sp": 0.62,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 179.73,
        "payor_sp": 63.6,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DF1",
        "org_region": "Cape",
        "org_premium": 2808.58,
        "org_pp": 5.84,
        "org_sp": 97.46,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 8.51,
        "payor_sp": 36.7,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DF1",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 174.41,
        "org_sp": 96.56,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 57.69,
        "payor_sp": 51.45,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 123.62,
        "org_sp": 69.64,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 23.7,
        "payor_sp": 73.1,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 120.54,
        "org_sp": 79.08,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 150.59,
        "payor_sp": 89.06,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 178.15,
        "org_pp": 147.7,
        "org_sp": 75.63,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 171.44,
        "payor_sp": 19.56,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 6755.9,
        "org_pp": 84.86,
        "org_sp": 46.58,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 139.1,
        "payor_sp": 19.26,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC1",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 187.98,
        "org_sp": 5.05,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 181.2,
        "payor_sp": 39.23,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 83.21,
        "org_sp": 63.7,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 152.39,
        "payor_sp": 26.81,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 6755.9,
        "org_pp": 47.4,
        "org_sp": 24.72,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 106.55,
        "payor_sp": 96.38,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 2808.58,
        "org_pp": 54.72,
        "org_sp": 51.67,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 127.29,
        "payor_sp": 13.2,
        "payor_paid": 6381.58,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Brianna",
    "lastName": "Cardenas",
    "mmis_id": 100029668141,
    "cca_id": 5361676065,
    "dob": "1983-01-17",
    "enrollmentStart": "2017-12-01",
    "enrollmentEnd": "2019-02-01",
    "ratecell": "CWD",
    "region": "Boston",
    "org_premium": 842.29,
    "org_pp": 12.31,
    "org_sp": 90.42,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-10-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 168.66,
        "org_sp": 0.96,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 139.2,
        "payor_sp": 39.39,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 6755.9,
        "org_pp": 6.29,
        "org_sp": 53.32,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 2371.4,
        "payor_pp": 163.92,
        "payor_sp": 56.85,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-06-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 6755.9,
        "org_pp": 95.45,
        "org_sp": 97.6,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 55.48,
        "payor_sp": 30.35,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 842.29,
        "org_pp": 115.63,
        "org_sp": 89.38,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 4.01,
        "payor_sp": 29.62,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 22.43,
        "org_sp": 77.42,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 2371.4,
        "payor_pp": 124.72,
        "payor_sp": 94.21,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-04-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 159.49,
        "org_sp": 18.21,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 103.42,
        "payor_sp": 92.91,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 562.18,
        "org_pp": 132.61,
        "org_sp": 36.55,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 186.6,
        "payor_sp": 53.23,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC1",
        "org_region": "Cape",
        "org_premium": 178.15,
        "org_pp": 164.03,
        "org_sp": 84.46,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 2371.4,
        "payor_pp": 68.69,
        "payor_sp": 90.99,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 28.41,
        "org_sp": 92.81,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 64.38,
        "payor_sp": 39.17,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DC2A",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 36.69,
        "org_sp": 27.75,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 4.24,
        "payor_sp": 2.73,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 36.7,
        "org_sp": 44.29,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 45.03,
        "payor_sp": 63.95,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 96.21,
        "org_sp": 75.43,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 125.02,
        "payor_sp": 47.87,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DF1",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 185.54,
        "org_sp": 40.93,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 137.18,
        "payor_sp": 97.38,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-07-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 48.86,
        "org_sp": 85.52,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 177.7,
        "payor_sp": 14.4,
        "payor_paid": 6381.58,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Debbie",
    "lastName": "Greene",
    "mmis_id": 100029141469,
    "cca_id": 5364292013,
    "dob": "1972-10-30",
    "enrollmentStart": "2017-04-01",
    "enrollmentEnd": "2019-04-01",
    "ratecell": "DC2A",
    "region": "Boston",
    "org_premium": 842.29,
    "org_pp": 28.95,
    "org_sp": 27.9,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-03-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 842.29,
        "org_pp": 2.42,
        "org_sp": 47.68,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 166.21,
        "payor_sp": 93.9,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Bridget",
    "lastName": "Spence",
    "mmis_id": 100071366284,
    "cca_id": 5362267657,
    "dob": "1989-05-17",
    "enrollmentStart": "2017-10-01",
    "enrollmentEnd": "2018-09-01",
    "ratecell": "DC2B",
    "region": "NA",
    "org_premium": 6755.9,
    "org_pp": 181.86,
    "org_sp": 47.03,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-03-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 174.84,
        "org_sp": 28.74,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 174.81,
        "payor_sp": 99.83,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 99.81,
        "org_sp": 79.99,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 2371.4,
        "payor_pp": 29.1,
        "payor_sp": 3.42,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 562.18,
        "org_pp": 20.72,
        "org_sp": 44.27,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 166.03,
        "payor_sp": 52.58,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 103.57,
        "org_sp": 11.28,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 30.46,
        "payor_sp": 43.13,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 33.02,
        "org_sp": 89.47,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 144.4,
        "payor_sp": 24.61,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-06-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 48.74,
        "org_sp": 57.33,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 154.6,
        "payor_sp": 85.98,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-08-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 49.72,
        "org_sp": 98.62,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 93.23,
        "payor_sp": 78.91,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 145.82,
        "org_sp": 60.36,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 75.76,
        "payor_sp": 72.01,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-10-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 188.87,
        "org_sp": 91.1,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 2371.4,
        "payor_pp": 116.59,
        "payor_sp": 60.98,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 154.68,
        "org_sp": 21.39,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 7.95,
        "payor_sp": 83.65,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 2808.58,
        "org_pp": 134.03,
        "org_sp": 76.31,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 118,
        "payor_sp": 81.84,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-06-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 107.3,
        "org_sp": 80.27,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 69.67,
        "payor_sp": 21.65,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-06-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 95.67,
        "org_sp": 34.34,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 170.34,
        "payor_sp": 79.4,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 2808.58,
        "org_pp": 169.58,
        "org_sp": 82.06,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 2371.4,
        "payor_pp": 166.69,
        "payor_sp": 87.45,
        "payor_paid": 2371.4,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Townsend",
    "lastName": "Delaney",
    "mmis_id": 100083744223,
    "cca_id": 5362054978,
    "dob": "1959-07-02",
    "enrollmentStart": "2017-09-01",
    "enrollmentEnd": "2019-04-01",
    "ratecell": "DF1",
    "region": "State",
    "org_premium": 842.29,
    "org_pp": 181.9,
    "org_sp": 52.94,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DF1",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 8.88,
        "org_sp": 81.34,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 157.33,
        "payor_sp": 50.17,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 6755.9,
        "org_pp": 58.75,
        "org_sp": 51.38,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 173.57,
        "payor_sp": 73.18,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2A",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 174.58,
        "org_sp": 61.93,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 109.16,
        "payor_sp": 56.68,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 81.78,
        "org_sp": 14.26,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 165.84,
        "payor_sp": 42.49,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-06-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 63.75,
        "org_sp": 39.52,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 19.81,
        "payor_sp": 34.76,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 86.36,
        "org_sp": 53.41,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 13.49,
        "payor_sp": 45.65,
        "payor_paid": 328.36,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Kelly",
    "lastName": "Branch",
    "mmis_id": 100068654233,
    "cca_id": 5361819895,
    "dob": "1979-07-17",
    "enrollmentStart": "2018-05-01",
    "enrollmentEnd": "2019-01-01",
    "ratecell": "DC1",
    "region": "East",
    "org_premium": 6755.9,
    "org_pp": 19.42,
    "org_sp": 81.97,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-06-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 164.47,
        "org_sp": 99.97,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 27.9,
        "payor_sp": 11.04,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Catalina",
    "lastName": "Underwood",
    "mmis_id": 100061955296,
    "cca_id": 5362213850,
    "dob": "1974-07-05",
    "enrollmentStart": "2017-02-01",
    "enrollmentEnd": "2019-04-01",
    "ratecell": "CWD",
    "region": "Non-Bos",
    "org_premium": 2808.58,
    "org_pp": 100.42,
    "org_sp": 89.8,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-07-01",
        "org_ratecell": "DC1",
        "org_region": "Cape",
        "org_premium": 2808.58,
        "org_pp": 154.16,
        "org_sp": 64.24,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 85.48,
        "payor_sp": 80.78,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 55.82,
        "org_sp": 10.86,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 56.2,
        "payor_sp": 35.58,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 128.81,
        "org_sp": 76.18,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 109.59,
        "payor_sp": 80.67,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 49.85,
        "org_sp": 51.74,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 95.13,
        "payor_sp": 88.7,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-08-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 14.97,
        "org_sp": 45.9,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 81.31,
        "payor_sp": 22.22,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-10-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 29.35,
        "org_sp": 50.55,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 79.92,
        "payor_sp": 7.77,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 6755.9,
        "org_pp": 74.3,
        "org_sp": 32.31,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 52.82,
        "payor_sp": 80.81,
        "payor_paid": 549.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Wise",
    "lastName": "Love",
    "mmis_id": 100079297935,
    "cca_id": 5363723254,
    "dob": "1983-04-16",
    "enrollmentStart": "2017-04-01",
    "enrollmentEnd": "2019-05-01",
    "ratecell": "DC2A",
    "region": "State",
    "org_premium": 2808.58,
    "org_pp": 69.63,
    "org_sp": 50.42,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC1",
        "org_region": "East",
        "org_premium": 562.18,
        "org_pp": 67.61,
        "org_sp": 52.16,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 46.39,
        "payor_sp": 57.43,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-03-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 57.29,
        "org_sp": 43.21,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 128.66,
        "payor_sp": 26.69,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 186.67,
        "org_sp": 42.95,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 133.56,
        "payor_sp": 71.37,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 108.99,
        "org_sp": 21.86,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 12.52,
        "payor_sp": 74.87,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 24.66,
        "org_sp": 84.02,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 74.42,
        "payor_sp": 8.2,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 24.34,
        "org_sp": 85.24,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 117.71,
        "payor_sp": 52.93,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 562.18,
        "org_pp": 174.21,
        "org_sp": 23.89,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 39.11,
        "payor_sp": 93.75,
        "payor_paid": 328.36,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Viola",
    "lastName": "Gardner",
    "mmis_id": 100038733965,
    "cca_id": 5367603844,
    "dob": "1975-12-19",
    "enrollmentStart": "2017-04-01",
    "enrollmentEnd": "2019-01-01",
    "ratecell": "TCD2",
    "region": "West",
    "org_premium": 2808.58,
    "org_pp": 41.41,
    "org_sp": 0.95,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 562.18,
        "org_pp": 143.82,
        "org_sp": 13.16,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 6381.58,
        "payor_pp": 173.57,
        "payor_sp": 12.79,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-10-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 842.29,
        "org_pp": 180.74,
        "org_sp": 11.58,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 159.46,
        "payor_sp": 92.44,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 178.15,
        "org_pp": 91.3,
        "org_sp": 54.11,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 2371.4,
        "payor_pp": 54.96,
        "payor_sp": 41.34,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 97,
        "org_sp": 44.51,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 181.2,
        "payor_sp": 83.56,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 90.25,
        "org_sp": 78.22,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 137.76,
        "payor_sp": 79.66,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-10-01",
        "org_ratecell": "DC2B",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 89.83,
        "org_sp": 80.03,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 149.97,
        "payor_sp": 28.85,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-06-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 113.12,
        "org_sp": 71.9,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 43.81,
        "payor_sp": 77.52,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 6.7,
        "org_sp": 71.34,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 189.08,
        "payor_sp": 32.22,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 178.15,
        "org_pp": 57.93,
        "org_sp": 83.66,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 137.69,
        "payor_sp": 62.26,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC2A",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 117.22,
        "org_sp": 65.1,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 70.21,
        "payor_sp": 52.44,
        "payor_paid": 6381.58,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Georgette",
    "lastName": "Quinn",
    "mmis_id": 100040467225,
    "cca_id": 5362669988,
    "dob": "1976-05-28",
    "enrollmentStart": "2018-03-01",
    "enrollmentEnd": "2018-12-01",
    "ratecell": "DC1",
    "region": "Non-Bos",
    "org_premium": 842.29,
    "org_pp": 55.46,
    "org_sp": 98.52,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 169.34,
        "org_sp": 87.53,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 45.29,
        "payor_sp": 86.89,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 187.08,
        "org_sp": 24.39,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 66.71,
        "payor_sp": 95.48,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-07-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 17.08,
        "org_sp": 77.02,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 549.18,
        "payor_pp": 94.77,
        "payor_sp": 71.46,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DF1",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 170.91,
        "org_sp": 45.9,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 70.49,
        "payor_sp": 86.04,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 562.18,
        "org_pp": 70.16,
        "org_sp": 12.49,
        "payor_ratecell": "CAM",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 139.83,
        "payor_sp": 42.98,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 51.54,
        "org_sp": 74.55,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 46.41,
        "payor_sp": 13.96,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Melody",
    "lastName": "Walsh",
    "mmis_id": 100057121737,
    "cca_id": 5367512392,
    "dob": "1986-04-24",
    "enrollmentStart": "2017-03-01",
    "enrollmentEnd": "2018-07-01",
    "ratecell": "CAM",
    "region": "Non-Bos",
    "org_premium": 6755.9,
    "org_pp": 165.1,
    "org_sp": 11.36,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 842.29,
        "org_pp": 65.56,
        "org_sp": 0.3,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 2371.4,
        "payor_pp": 127.19,
        "payor_sp": 50.6,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC1",
        "org_region": "West",
        "org_premium": 6755.9,
        "org_pp": 22.74,
        "org_sp": 63.67,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 24.98,
        "payor_sp": 77.34,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-03-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 178.15,
        "org_pp": 44.72,
        "org_sp": 17.41,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 158.45,
        "payor_sp": 33.05,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-03-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 562.18,
        "org_pp": 19.96,
        "org_sp": 22.9,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 181.32,
        "payor_sp": 20.96,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-04-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 178.15,
        "org_pp": 134.13,
        "org_sp": 31.08,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 2371.4,
        "payor_pp": 111.85,
        "payor_sp": 33.59,
        "payor_paid": 2371.4,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-07-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 125.82,
        "org_sp": 29.78,
        "payor_ratecell": "R2D2",
        "payor_region": "Non-Bos",
        "payor_premium": 549.18,
        "payor_pp": 38.2,
        "payor_sp": 51.09,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 1.91,
        "org_sp": 87.48,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 161.27,
        "payor_sp": 93.56,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-06-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 132.14,
        "org_sp": 91.6,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 106.97,
        "payor_sp": 33.93,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC2A",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 55.01,
        "org_sp": 69.8,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 6381.58,
        "payor_pp": 136.32,
        "payor_sp": 36.85,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-03-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 146.78,
        "org_sp": 84.48,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 167.73,
        "payor_sp": 2.75,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-06-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 61.36,
        "org_sp": 19.93,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 7.86,
        "payor_sp": 25.91,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-08-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 161.14,
        "org_sp": 25.11,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 171.45,
        "payor_sp": 42.02,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Patty",
    "lastName": "Abbott",
    "mmis_id": 100041774103,
    "cca_id": 5361644875,
    "dob": "1989-12-29",
    "enrollmentStart": "2017-02-01",
    "enrollmentEnd": "2019-02-01",
    "ratecell": "DF1",
    "region": "Boston",
    "org_premium": 842.29,
    "org_pp": 64.17,
    "org_sp": 24.58,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC2A",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 6.25,
        "org_sp": 39.87,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 164.15,
        "payor_sp": 31.74,
        "payor_paid": 6381.58,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-11-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 562.18,
        "org_pp": 35.49,
        "org_sp": 84.8,
        "payor_ratecell": "CWD",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 136.73,
        "payor_sp": 76.34,
        "payor_paid": 328.36,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Ollie",
    "lastName": "Hendrix",
    "mmis_id": 100028099137,
    "cca_id": 5366438307,
    "dob": "1980-02-08",
    "enrollmentStart": "2017-06-01",
    "enrollmentEnd": "2019-04-01",
    "ratecell": "R2D2",
    "region": "State",
    "org_premium": 562.18,
    "org_pp": 110.51,
    "org_sp": 61.37,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 178.15,
        "org_pp": 110.33,
        "org_sp": 65.94,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 135.87,
        "payor_sp": 43.67,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-01-01",
        "org_ratecell": "DC2A",
        "org_region": "East",
        "org_premium": 2808.58,
        "org_pp": 150.58,
        "org_sp": 16.83,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 47.17,
        "payor_sp": 41.78,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC1",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 94.09,
        "org_sp": 66.91,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 8303.18,
        "payor_pp": 78.17,
        "payor_sp": 95.54,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Kris",
    "lastName": "Harding",
    "mmis_id": 100039127746,
    "cca_id": 5363460778,
    "dob": "1972-11-08",
    "enrollmentStart": "2017-11-01",
    "enrollmentEnd": "2019-01-01",
    "ratecell": "DC1",
    "region": "Non-Bos",
    "org_premium": 562.18,
    "org_pp": 1.25,
    "org_sp": 68.29,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DC2B",
        "org_region": "East",
        "org_premium": 6755.9,
        "org_pp": 1.06,
        "org_sp": 55.9,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 77.52,
        "payor_sp": 34.36,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC2B",
        "org_region": "Cape",
        "org_premium": 6755.9,
        "org_pp": 94.17,
        "org_sp": 47.29,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 93.83,
        "payor_sp": 4.65,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC1",
        "org_region": "Cape",
        "org_premium": 178.15,
        "org_pp": 78.75,
        "org_sp": 7.76,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 82.74,
        "payor_sp": 91.22,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-12-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 842.29,
        "org_pp": 39.22,
        "org_sp": 63.24,
        "payor_ratecell": "TCD2",
        "payor_region": "Non-Bos",
        "payor_premium": 328.36,
        "payor_pp": 23.65,
        "payor_sp": 61.33,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DC2A",
        "org_region": "East",
        "org_premium": 178.15,
        "org_pp": 164.46,
        "org_sp": 8.76,
        "payor_ratecell": "CWD",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 8.26,
        "payor_sp": 12.94,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-04-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 103.49,
        "org_sp": 45.01,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 8303.18,
        "payor_pp": 184.87,
        "payor_sp": 53.91,
        "payor_paid": 8303.18,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Sears",
    "lastName": "Ramos",
    "mmis_id": 100049299518,
    "cca_id": 5360653052,
    "dob": "1976-07-13",
    "enrollmentStart": "2017-06-01",
    "enrollmentEnd": "2018-11-01",
    "ratecell": "R2D2",
    "region": "NA",
    "org_premium": 842.29,
    "org_pp": 83.9,
    "org_sp": 30.53,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-02-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 6755.9,
        "org_pp": 189.45,
        "org_sp": 42.48,
        "payor_ratecell": "R2D2",
        "payor_region": "Boston",
        "payor_premium": 8303.18,
        "payor_pp": 113.32,
        "payor_sp": 54.79,
        "payor_paid": 8303.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DF1",
        "org_region": "State",
        "org_premium": 562.18,
        "org_pp": 181.51,
        "org_sp": 19.02,
        "payor_ratecell": "CWD",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 57.52,
        "payor_sp": 49.27,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-09-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 178.15,
        "org_pp": 45.2,
        "org_sp": 66.13,
        "payor_ratecell": "CAM",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 83.39,
        "payor_sp": 69.57,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-06-01",
        "org_ratecell": "DC2A",
        "org_region": "State",
        "org_premium": 2808.58,
        "org_pp": 25.16,
        "org_sp": 84.31,
        "payor_ratecell": "CAM",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 119.77,
        "payor_sp": 4.03,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-07-01",
        "org_ratecell": "DC1",
        "org_region": "East",
        "org_premium": 842.29,
        "org_pp": 0.61,
        "org_sp": 7.88,
        "payor_ratecell": "TCD2",
        "payor_region": "Boston",
        "payor_premium": 328.36,
        "payor_pp": 109.9,
        "payor_sp": 49.57,
        "payor_paid": 328.36,
        "variance": 0
      }
    ]
  },
  {
    "program": "ICO",
    "firstName": "Vasquez",
    "lastName": "Kent",
    "mmis_id": 100024025837,
    "cca_id": 5367238708,
    "dob": "1960-01-27",
    "enrollmentStart": "2017-02-01",
    "enrollmentEnd": "2019-02-01",
    "ratecell": "DF1",
    "region": "Cape",
    "org_premium": 842.29,
    "org_pp": 43.1,
    "org_sp": 73.8,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-05-01",
        "org_ratecell": "DC2B",
        "org_region": "West",
        "org_premium": 842.29,
        "org_pp": 174.93,
        "org_sp": 23.31,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 549.18,
        "payor_pp": 171.32,
        "payor_sp": 94.72,
        "payor_paid": 549.18,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-04-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 842.29,
        "org_pp": 123.34,
        "org_sp": 17.31,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 328.36,
        "payor_pp": 178.33,
        "payor_sp": 17.4,
        "payor_paid": 328.36,
        "variance": 0
      },
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2018-07-01",
        "org_ratecell": "DF1",
        "org_region": "East",
        "org_premium": 842.29,
        "org_pp": 77.22,
        "org_sp": 2.27,
        "payor_ratecell": "R2D2",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 119.95,
        "payor_sp": 36.25,
        "payor_paid": 6381.58,
        "variance": 0
      }
    ]
  },
  {
    "program": "SCO",
    "firstName": "Rebekah",
    "lastName": "Sweeney",
    "mmis_id": 100029708275,
    "cca_id": 5363839231,
    "dob": "1974-06-30",
    "enrollmentStart": "2017-02-01",
    "enrollmentEnd": "2019-04-01",
    "ratecell": "DC2A",
    "region": "State",
    "org_premium": 562.18,
    "org_pp": 146.62,
    "org_sp": 60.15,
    "total_d": 0,
    "amount": 0,
    "aging": 0,
    "discrepancies": [
      {
        "lastName": "",
        "firstName": "",
        "mmis_id": 0,
        "cca_id": 0,
        "program": "",
        "month": "2019-05-01",
        "org_ratecell": "DC1",
        "org_region": "State",
        "org_premium": 842.29,
        "org_pp": 127.49,
        "org_sp": 84.9,
        "payor_ratecell": "TCD2",
        "payor_region": "NA",
        "payor_premium": 6381.58,
        "payor_pp": 26.45,
        "payor_sp": 65.31,
        "payor_paid": 6381.58,
        "variance": 0
      }
    ]
  }
];
  
MemberData.forEach(member => {
      member.enrollmentEnd = 
      Math.floor(Math.random() * 10) != 1  ? '' :
          new Date(new Date(member.enrollmentEnd).getTime() - 86400000)
          .toISOString().slice(0, 10);

      member.total_d = member.discrepancies.length;
      member.discrepancies.forEach((d: DisElement) => {

        
        member.amount += d.variance;

        member.aging = (new Date().getTime() - new Date(d.month).getTime()) / 86400000 > member.aging 
        ? (new Date().getTime() - new Date(d.month).getTime()) / 86400000
        : member.aging;

        member.aging = Math.floor(member.aging);

        d.org_pp = d.org_pp * (Math.random() > 0.9 ?  1 : 0);
        d.org_sp = d.org_sp * (Math.random() > 0.9 ?  1 : 0);
        d.payor_pp = d.payor_pp * (Math.random() > 0.9 ?  1 : 0);
        d.payor_sp = d.payor_sp * (Math.random() > 0.9 ?  1 : 0);
        d.payor_paid = (d.payor_premium - (Math.random() > 0.8 ?  62.03 : 0)) - d.payor_pp - d.payor_sp;



        d.variance = d.payor_paid - (d.org_premium - d.org_pp - d.org_sp);
        d.program  = member.program;
        d.firstName = member.firstName;
        d.lastName = member.lastName;
        d.mmis_id = member.mmis_id;
        d.cca_id = member.cca_id;
      });
    }
  );

  export const ELEMENT_DATA: PeriodicElement[] = MemberData;

  export const D_DATA: DisElement[] = ELEMENT_DATA
  .map(e => e.discrepancies)
  .reduce((a, b) => a.concat(b));

  const JSON_FEED_MEM_DIS = 
  [
    '{{repeat(20)}}',
    {
      program: '{{random("ICO", "SCO")}}',
      firstName: '{{firstName()}}',
      lastName: '{{surname()}}',
      mmis_id: '{{integer(100019999999, 100099999999)}}',
      cca_id: '{{integer(5360000000, 5368888888)}}',
      dob: '{{date(new Date(1957, 0, 1), new Date(1990, 5, 1), "YYYY-MM-dd")}}',
      enrollmentStart: '{{date(new Date(2017, 0, 1), new Date(2018, 5, 1), "YYYY-MM-01")}}',
      enrollmentEnd: '{{date(new Date(2018, 6, 1), new Date(2019, 5, 1), "YYYY-MM-01")}}',
      ratecell: '{{random("DC1", "DC2A", "DC2B", "DF1", "CWD", "CAM", "R2D2", "TCD2")}}',
       region: '{{random("East", "West", "State", "Cape" , "Boston", "Non-Bos", "NA")}}',
      org_premium: '{{random(178.15, 562.18, 842.29, 2808.58, 6755.90)}}',
      org_pp: '{{floating(0, 190, 2)}}',
      org_sp: '{{floating(0, 100, 2)}}',
      total_d: 0,
      amount: 0,
      aging: 0,
      discrepancies: [
        '{{repeat(1,14)}}', 
    {
          month: '{{date(new Date(2018, 2, 1), new Date(), "YYYY-MM-01")}}',
        org_ratecell: '{{random("DC1", "DC2A", "DC2B", "DF1")}}',
         org_region: '{{random("East", "West", "State", "Cape")}}',
         org_premium: '{{random(178.15, 562.18, 842.29, 2808.58, 6755.90)}}',
        org_pp: '{{floating(0, 190, 2)}}',
        org_sp: '{{floating(0, 100, 2)}}',
        payor_ratecell: '{{random("CWD", "CAM", "R2D2", "TCD2")}}',
        payor_region: '{{random("Boston", "Non-Bos", "NA")}}',
        payor_premium: '{{random(328.36, 549.18, 2371.40, 6381.58,  8303.18 )}}',
        payor_pp: '{{floating(0, 190, 2)}}',
        payor_sp: '{{floating(0, 100, 2)}}',
        payor_paid: function() {
          return this.payor_premium; 
        },
        variance: 0
        }
      ]
    }
  ]

  const JSON_FEED_COMMENTARY =
  [
    '{{repeat(5, 7)}}',
    {
      _id: '{{objectId()}}',
      reply_id:'',
      name: '{{firstName()}} {{surname()}}',
      content: '{{lorem(1, "paragraphs")}}',
      created_at: '{{date(new Date(2019, 5, 1), new Date(), "YYYY-MM-ddThh:mm:ss Z")}}',
      updated_at: ''
    }
  ]
  export interface CommentaryElement {
    _id: string;
    reply_id: string;
    name: string;
    content: string;
    created_at: string;
    updated_at: string;
  }

  export interface MasterCommentaryElement {
    _id: string;
    reply_id: string;
    name: string;
    content: string;
    created_at: string;
    updated_at: string;
    sub_commentaries: CommentaryElement[];
  }

const C_ELEMENT_DATA = [
  {
    "_id": "5d24ead06379f32e7ec12da7",
    "reply_id": "",
    "name": "Marina Daugherty",
    "content": "Fugiat ea dolore laborum incididunt Lorem reprehenderit voluptate. Ea aliquip consequat minim culpa. Nostrud consequat anim ex elit magna ullamco ipsum Lorem consequat incididunt proident commodo veniam. Excepteur minim nostrud culpa cillum veniam consequat duis elit eiusmod quis proident amet culpa nostrud. Fugiat do magna est Lorem ullamco. Dolor pariatur eiusmod esse duis aliqua nostrud nulla dolore. Eu mollit ut cupidatat proident elit aliqua ad qui id ipsum consequat.\r\n",
    "created_at": "2019-06-28T01:03:54",
    "updated_at": ""
  },
  {
    "_id": "5d24ead05f71f35219a13b43",
    "reply_id": "5d24ead06379f32e7ec12da7",
    "name": "Magdalena Wilson",
    "content": "Lorem irure nisi adipisicing minim tempor ea laboris incididunt deserunt est. Proident incididunt dolore fugiat ullamco aliquip commodo occaecat esse cillum ex cupidatat Lorem qui incididunt. Occaecat elit laboris eu proident quis eiusmod quis sunt pariatur nostrud voluptate. Nostrud cupidatat in voluptate eiusmod adipisicing consequat enim fugiat.\r\n",
    "created_at": "2019-07-02T06:11:39",
    "updated_at": ""
  },
  {
    "_id": "5d24ead046d710811846875f",
    "reply_id": "",
    "name": "Rosario Head",
    "content": "Id nostrud Lorem officia dolore nisi consequat ullamco ullamco minim qui laborum. Minim velit excepteur ex laborum eiusmod sit ad dolore eu amet proident laborum. Officia cillum Lorem est ut ut Lorem incididunt in aute ex laborum esse laborum. Nulla nostrud incididunt duis mollit consequat qui culpa cillum nisi tempor mollit culpa in. Exercitation ad sunt ullamco consequat ex exercitation ullamco excepteur. Consectetur veniam eiusmod id pariatur sunt sint reprehenderit Lorem anim velit in. Velit irure ipsum est est esse duis proident eu non.\r\n",
    "created_at": "2019-06-10T04:11:16",
    "updated_at": ""
  },
  {
    "_id": "5d24ead0591598fdce95ec1e",
    "reply_id": "",
    "name": "Yue Song",
    "content": "Est dolore labore non voluptate qui. Labore qui eu culpa non consectetur do excepteur dolor anim ut. Ea consequat ex veniam laboris cillum. Laboris duis nulla ullamco veniam velit aliquip dolor culpa ea exercitation dolore minim. Dolore occaecat magna est ut et Lorem esse pariatur esse incididunt. Ullamco voluptate nostrud aliquip minim. Eu et aliqua occaecat enim commodo est id dolor deserunt minim cillum.\r\n",
    "created_at": "2019-07-06T08:09:25",
    "updated_at": ""
  },
  {
    "_id": "5d24ead003af096486a18afd",
    "reply_id": "",
    "name": "Gomez Moses",
    "content": "Ad id mollit ad aliquip dolor tempor mollit aute veniam Lorem. Id dolor culpa nulla mollit nostrud ex proident. Eu cillum do laborum ex reprehenderit enim nostrud ea esse et occaecat eiusmod labore quis. Consectetur pariatur proident aute magna sit. Aliqua in Lorem aliqua fugiat cillum labore excepteur aute amet nisi velit. Ut sint laborum commodo pariatur veniam do occaecat irure do nisi deserunt consequat.\r\n",
    "created_at": "2019-06-22T05:08:06",
    "updated_at": ""
  },
  {
    "_id": "5d24ead0fcc0b20f35316239",
    "reply_id": "5d24ead02081703e7fb2ddff",
    "name": "Elba Austin",
    "content": "Aliquip ipsum elit labore incididunt duis ad laborum qui culpa veniam ea magna consequat minim. Elit elit fugiat ullamco eiusmod occaecat adipisicing sint nisi. Exercitation tempor dolor irure aute deserunt ex quis exercitation. Id et amet Lorem ad. Sunt fugiat irure cillum dolore id sit ex cupidatat proident sit exercitation. Cillum quis ad ut qui non labore dolor est id magna aute.\r\n",
    "created_at": "2019-06-20T03:08:53",
    "updated_at": ""
  },
  {
    "_id": "5d24ead02d4f664f7e302ff0",
    "reply_id": "5d24ead0591598fdce95ec1e",
    "name": "Dominguez Cleveland",
    "content": "Exercitation mollit aliquip sit esse commodo consectetur ex amet voluptate. Excepteur exercitation ad ullamco culpa sunt. Ex officia officia cupidatat est aute velit enim nulla excepteur velit consequat officia nostrud aliquip.\r\n",
    "created_at": "2019-07-08T11:07:34",
    "updated_at": ""
  },
  {
    "_id": "5d24ead01e089bd74e9c5f99",
    "reply_id": "5d24ead0591598fdce95ec1e",
    "name": "Yue Song",
    "content": "Aute ullamco do minim dolore quis consequat ullamco sunt proident velit qui. Nulla commodo nisi dolor magna consectetur deserunt ad dolore quis amet qui cupidatat elit cillum. Aliquip eu amet ex qui aute aute laborum voluptate in velit commodo. Sit fugiat consequat elit non ad.\r\n",
    "created_at": "2019-07-11T09:55:01",
    "updated_at": "2019-07-18T01:03:54"
  },
  {
    "_id": "5d24ead02081703e7fb2ddff",
    "reply_id": "",
    "name": "Hogan Dillon",
    "content": "Et cillum officia incididunt consequat cupidatat anim ut dolore dolor fugiat adipisicing. Proident non consectetur proident tempor ex deserunt dolore adipisicing cillum pariatur tempor duis duis. Officia culpa ad culpa deserunt amet ut voluptate id labore mollit fugiat. Nisi quis excepteur et labore aliquip. Ad sit in ut veniam. Veniam est aliqua qui mollit velit laboris eiusmod mollit duis ipsum. Deserunt quis officia cupidatat adipisicing enim consectetur proident irure.\r\n",
    "created_at": "2019-06-09T10:28:21",
    "updated_at": ""
  },
  {
    "_id": "5d24ead07fa95dceeaf0c800",
    "reply_id": "5d24ead046d710811846875f",
    "name": "Campos Manning",
    "content": "Tempor anim deserunt nostrud cupidatat enim enim magna veniam et mollit ea. Pariatur cillum do dolor cupidatat aute adipisicing reprehenderit magna veniam. Anim velit aliqua occaecat quis pariatur fugiat do proident exercitation ad veniam ullamco magna. Dolore dolor reprehenderit id velit cillum. Sit pariatur ullamco amet minim laboris officia laboris esse nisi commodo pariatur tempor.\r\n",
    "created_at": "2019-06-18T03:06:31",
    "updated_at": ""
  }
]


const sorted_c = C_ELEMENT_DATA.sort((a, b) => 
  new Date(a.created_at).getTime() - new Date(b.created_at).getTime());

export const C_DATA: CommentaryElement[] = sorted_c;
